# You can add one username per supported platform and one custom link
patreon: natterstefan
# open_collective: # Replace with your Open Collective username
# ko_fi: # Replace with your Ko-fi username
# custom: http://example.com
